blank_issues_enabled: false
contact_links: 
  - name: Community discussions
    url: https://github.com/Mann-Conomy/eslint-config/discussions/categories/q-a
    about: Please ask and answer questions here.
